apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nfs
    meta.helm.sh/release-namespace: storage
  creationTimestamp: "2025-05-26T02:53:58Z"
  generation: 1
  labels:
    app.kubernetes.io/component: controller-linux
    app.kubernetes.io/csi-role: controller
    app.kubernetes.io/instance: nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.15.0
  name: nfs-democratic-csi-controller
  namespace: storage
  resourceVersion: "6397"
  uid: e53c1ff2-e4fe-4f6d-8323-3d3ea49f9fbb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-linux
      app.kubernetes.io/csi-role: controller
      app.kubernetes.io/instance: nfs
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: democratic-csi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: 19cea2c79cc6053832ee624cba7b3b7d806b48d9cf5b832f8a1d94beea797de5
        checksum/secret: 16c667162d32d8b2f9b6ba8fbfe2b7e5aa80a6900e945b922f7fcd479812581f
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller-linux
        app.kubernetes.io/csi-role: controller
        app.kubernetes.io/instance: nfs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: democratic-csi
    spec:
      containers:
      - args:
        - --v=5
        - --leader-election
        - --leader-election-namespace=storage
        - --timeout=90s
        - --worker-threads=10
        - --csi-address=/csi-data/csi.sock
        image: registry.k8s.io/sig-storage/csi-attacher:v4.4.0
        imagePullPolicy: IfNotPresent
        name: external-attacher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - args:
        - --v=5
        - --leader-election
        - --leader-election-namespace=storage
        - --timeout=90s
        - --worker-threads=10
        - --extra-create-metadata
        - --csi-address=/csi-data/csi.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
        imagePullPolicy: IfNotPresent
        name: external-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - args:
        - --v=5
        - --leader-election
        - --leader-election-namespace=storage
        - --timeout=90s
        - --workers=10
        - --csi-address=/csi-data/csi.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.k8s.io/sig-storage/csi-resizer:v1.9.0
        imagePullPolicy: IfNotPresent
        name: external-resizer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - args:
        - --v=5
        - --leader-election
        - --leader-election-namespace=storage
        - --timeout=90s
        - --worker-threads=10
        - --csi-address=/csi-data/csi.sock
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
        imagePullPolicy: IfNotPresent
        name: external-snapshotter
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - args:
        - --csi-version=1.5.0
        - --csi-name=nfs
        - --driver-config-file=/config/driver-config-file.yaml
        - --log-level=info
        - --csi-mode=controller
        - --server-socket=/csi-data/csi.sock.internal
        env:
        - name: NODE_EXTRA_CA_CERTS
          value: /tmp/certs/extra-ca-certs.crt
        image: docker.io/democraticcsi/democratic-csi:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - bin/liveness-probe
            - --csi-version=1.5.0
            - --csi-address=/csi-data/csi.sock.internal
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 15
        name: csi-driver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - mountPath: /config
          name: config
        - mountPath: /tmp/certs
          name: extra-ca-certs
      - env:
        - name: BIND_TO
          value: unix:///csi-data/csi.sock
        - name: PROXY_TO
          value: unix:///csi-data/csi.sock.internal
        image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.6
        imagePullPolicy: IfNotPresent
        name: csi-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-democratic-csi-controller-sa
      serviceAccountName: nfs-democratic-csi-controller-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: socket-dir
      - name: config
        secret:
          defaultMode: 420
          secretName: nfs-democratic-csi-driver-config
      - configMap:
          defaultMode: 420
          items:
          - key: extra-ca-certs
            path: extra-ca-certs.crt
          name: nfs-democratic-csi
        name: extra-ca-certs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-26T02:54:40Z"
    lastUpdateTime: "2025-05-26T02:54:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-26T02:53:59Z"
    lastUpdateTime: "2025-05-26T02:54:40Z"
    message: ReplicaSet "nfs-democratic-csi-controller-75f6dc7f8c" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: nfs
    meta.helm.sh/release-namespace: storage
  creationTimestamp: "2025-05-26T02:53:58Z"
  generation: 1
  labels:
    app.kubernetes.io/component: node-linux
    app.kubernetes.io/csi-role: node
    app.kubernetes.io/instance: nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.15.0
  name: nfs-democratic-csi-node
  namespace: storage
  resourceVersion: "66230"
  uid: cd743aaf-94e4-4e84-92b1-a0f52cbe71b5
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: node-linux
      app.kubernetes.io/csi-role: node
      app.kubernetes.io/instance: nfs
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: democratic-csi
  template:
    metadata:
      annotations:
        checksum/configmap: 19cea2c79cc6053832ee624cba7b3b7d806b48d9cf5b832f8a1d94beea797de5
        checksum/secret: 16c667162d32d8b2f9b6ba8fbfe2b7e5aa80a6900e945b922f7fcd479812581f
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: node-linux
        app.kubernetes.io/csi-role: node
        app.kubernetes.io/instance: nfs
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: democratic-csi
    spec:
      containers:
      - args:
        - --csi-version=1.5.0
        - --csi-name=nfs
        - --driver-config-file=/config/driver-config-file.yaml
        - --log-level=info
        - --csi-mode=node
        - --server-socket=/csi-data/csi.sock.internal
        env:
        - name: CSI_NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NODE_EXTRA_CA_CERTS
          value: /tmp/certs/extra-ca-certs.crt
        image: docker.io/democraticcsi/democratic-csi:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - bin/liveness-probe
            - --csi-version=1.5.0
            - --csi-address=/csi-data/csi.sock.internal
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 15
        name: csi-driver
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /tmp/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /lib/modules
          name: modules-dir
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /run/udev
          name: udev-data
        - mountPath: /host
          mountPropagation: Bidirectional
          name: host-dir
        - mountPath: /sys
          name: sys-dir
        - mountPath: /dev
          name: dev-dir
        - mountPath: /config
          name: config
        - mountPath: /tmp/certs
          name: extra-ca-certs
      - env:
        - name: BIND_TO
          value: unix:///csi-data/csi.sock
        - name: PROXY_TO
          value: unix:///csi-data/csi.sock.internal
        image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.6
        imagePullPolicy: IfNotPresent
        name: csi-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=/csi-data/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/nfs/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /csi-node-driver-registrar
            - --kubelet-registration-path=/var/lib/kubelet/plugins/nfs/csi.sock
            - --mode=kubelet-registration-probe
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
        - mountPath: /var/lib/kubelet
          name: kubelet-dir
      - args:
        - while true; do sleep 2; done;
        command:
        - /bin/sh
        - -c
        - --
        image: docker.io/busybox:1.37.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /plugins/nfs /registration/nfs-reg.sock
        name: cleanup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugins
          name: plugins-dir
        - mountPath: /registration
          name: registration-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-democratic-csi-node-sa
      serviceAccountName: nfs-democratic-csi-node-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/nfs
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: plugins-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /dev
          type: Directory
        name: dev-dir
      - hostPath:
          path: /lib/modules
          type: ""
        name: modules-dir
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /run/udev
          type: ""
        name: udev-data
      - hostPath:
          path: /sys
          type: Directory
        name: sys-dir
      - hostPath:
          path: /
          type: Directory
        name: host-dir
      - name: config
        secret:
          defaultMode: 420
          secretName: nfs-democratic-csi-driver-config
      - configMap:
          defaultMode: 420
          items:
          - key: extra-ca-certs
            path: extra-ca-certs.crt
          name: nfs-democratic-csi
        name: extra-ca-certs
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 2
  numberMisscheduled: 0
  numberReady: 2
  observedGeneration: 1
  updatedNumberScheduled: 2