kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs
  namespace: debug
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
