apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: joplin
spec:
  selector:
    app: joplin
  ports:
    - name: http
      port: 22300
      targetPort: 22300