apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: joplin
spec:
  selector:
    app: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: joplin
  namespace: joplin
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  type: LoadBalancer
  selector:
    app: joplin
  ports:
    - name: http
      port: 80
      targetPort: 22300
  externalTrafficPolicy: Cluster