apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: POSTGRES_DATABASE
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin
  namespace: joplin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin
  template:
    metadata:
      labels:
        app: joplin
    spec:
      containers:
        - name: joplin
          image: joplin/server:latest
          ports:
            - containerPort: 22300
          env:
            - name: APP_PORT
              value: "22300"
            - name: APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: APP_BASE_URL
            - name: DB_CLIENT
              value: pg
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: POSTGRES_DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: joplin-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: db
