apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: joplin-crd
spec:
  hostAPI: https://infisical.trochalakis.net/api
  authentication:
      universalAuth:
          secretsScope:
              projectSlug: kubernetes-pa-gn # <-- project slug
              envSlug: prod # "dev", "staging", "prod", etc..
              secretsPath: "/joplin" # Root is "/"
          credentialsRef:
              secretName: universal-auth-credentials # <-- name of the Kubernetes secret that stores our machine identity credentials
              secretNamespace: default # <-- namespace of the Kubernetes secret that stores our machine identity credentials
  managedKubeSecretReferences:
    - secretName: joplin-secrets
      secretNamespace: joplin
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          NEW_KEY_NAME: "{{ .KEY.SecretPath }} {{ .KEY.Value }}"
          KEY_WITH_BINARY_VALUE: "{{ .KEY.SecretPath }} {{ .KEY.Value }}"