apiVersion: v1
kind: Service
metadata:
  name: sftpgo
  namespace: sftpgo
spec:
  selector:
    app: sftpgo
  ports:
    - name: sftp
      port: 2022
      targetPort: 2022
    - name: web
      port: 8080
      targetPort: 8080
  type: LoadBalancer