apiVersion: v1
kind: Service
metadata:
  name: apt-cacher-ng
  namespace: apt-cacher-ng
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  selector:
    app: apt-cacher-ng
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3142
  externalTrafficPolicy: Cluster