apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: apt-cacher-ng
  namespace: apt-cacher-ng
  annotations:
    volume.alpha.kubernetes.io/storage-class: "generic"
  labels:
    app.kubernetes.io/name: apt-cacher-ng
    app.kubernetes.io/instance: apt-cacher-ng
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "32Gi"