---
# Source: harbor/templates/core/core-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-core
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  secretKey: "bm90LWEtc2VjdXJlLWtleQ=="
  secret: "c1l6c0dTS1NFcm1EYnRjZw=="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBd2ZWVVArWTgvOEh4Z0RuTlNqYTFobytqd0hhb2E5eEhkQ05UR0RQRkVGR0wrV2h3CjB6T3ROd2JMckNYZmVaRDNiZCsyRzlKYmk1amdlOGhsR2RFWmRzWmVMczZoYUlpdTVqS2YvdjBoM0ljb1pXNkcKY2hNRHZicWVsMk9oME9vNlhkU3ZvRE9kTG5LTTVPWE5ENWRWVXMwTWl6cEtWTEU4SFV5SENYWUJSWWgzN0hVeApXQ05PbXg5aS9pMExKNWtPVUxmR0drelFoVmwvaHVKWjh4QnVDcFYyT3VHQUYwamxLTFJlaE00QW1WUUNzbXljClpTaWlGK3lHKzFSaDNjZkdaY2FDNWJLRUdPQ2RKNU53dDdaa0QzZVhLRVl3QldiY1hVb2hQN0JzY3NrSlhrWkoKZitid1JqSGxnbXdhYXpFUVhCVEFtMjc3ekdVSUU5aTEyREFWY1FJREFRQUJBb0lCQUFNcmJqQUpKREFOekZPTApIa2E3TkNZNXpMUkZmQ1VmR1cvVmIvTXlUV01oNGdhMlpUbWVXNU5Ob2lCekVmN2JscCtPQzF6VENEbjB5cDViClBRTzUvZytKMkZvdGVFZk1EQWVwQmlKVm9xc0c3bXNSN2xLSTZ3Tzd2QUcvV0JLZzhVazlRNDE3cW5McTNsQ1QKVE5HWGFJYU00VXFaTGtQS0RiQnc0cmdOM0tGMVBTY0FIYzVuQVNuaHFSc3I0TWJiUFNEMzRxWkdhSllkRXlGdgpReGlLcXQvNW9Ha2RkWWROY0xJNTNNaUxldjh0Qm5tSC9YQWRqT0M3N3RsS2c3eVN2RTJjdVYyR0RDNGVCd25ECm44bStKSzlUTjdldE9rZEFoVlVyeTFBZnZEam84aGRyaTA0aVM0MlIyVzc4Q0RtTDMrbTBFMnZyWGJEOFQ3d1YKTlFsdTVjRUNnWUVBOWRjSy9JNmg3NDQzc1Zra3V1eUpNaU95UlEvNTkvL2Y0aHVRU2orQmRHMWhZVGNQUURrdgplNEQ3ZWFrMmRzZ3FtOGZRZ1Y3NlVnT0gyR0thczdDeURwYXZWbUxiM0o5cmJLcndCaThKck5jbmZiclBmN2U3CmtPaWdSSlBUYlM1Ym9TKzhMQk1oWWxtTGlLcGd5NGZKZWlyNTRmdW1GcE50VDFyZVBuTk9BdmtDZ1lFQXlmbGkKWFV4TXBrN3JTRVhuR2N1cnRlRzVXRjM0U1hVUUpSRGZyYjhXcE5nZnJDU1pjaDdpTW9UdDlNWitqTVI4NkJrYgovbERDd0ZyenVKVU5rcXF6Z2JTTlFuRkthajVlTkpta1BZSTh2M2xhSU56ZFBpd0RtSDhtaFBlZnVSUGRSYXlZClNJYnIzN1Jod3JYQWNTdVJUcFYvOHZGWUtySW5tQjdSa0ZiTHpEa0NnWUVBcVIvOW9PNEhIYVM3VDdqQitnNkwKL0FCdXZmQlZ5WFV3Y243Lzd2UnRmTWxhK3VSRUM2ekxxNjE2VTZKRG84ZmsrREtva0xma2dkT0greWNxd24vRwpueDZ2RlVFQmZHLzRHVlFudURsWDhKNDd2dFZydHJPUnlBa2hhTXhCNFpUSTJNVGNNWDRmczJkakJPd2hseU9kClNmeVMyQktsbWxabUZ2ZXVlVXdkMlJFQ2dZRUFuS1M1MFRvM3lGUTB6bHpJbTQwR280MXBQa3ZESU5XVnErbW0KVVE1KzlXSlpUaDBrbFFtMnpRK2pyYyswbm1CVnIzeXA1VmVsYzZJV20vV2VEVDR1OGsyaHNRSkVnSm5XWGwwNgpzQ211QzZLR2NDNWJ1TGhTSVplYnZFeUFwLzNzQXZtVk1jclNiVEZ0RUtIOW1zZjdia01zZExNUmVpdXA0YVVsClN4akYvcUVDZ1lCU1VVenB0MTBRWnpIY2xkT2dBZkhmYTVaNWpFSWFRQUZIbmt2c3pwU3lKSWZseklUdjV0Wk8KbjFJcWpZc3JGMjJyNVhQZm9DOEpQcjlsQUFxaHN2WkErZGozRnNMS2o2a3hkUUhpemRXMVhIZ2IwS0NiTFR6RApGei9OSVVNZ21HVHpKQ1pOdE4reFhmRnhHenluMjIwNFVia0x1d3c0eHNzSmhhbENFWlNCQWc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lRU1ovcFpzVmpVZWgxOGF6MGlrcy9JakFOQmdrcWhraUc5dzBCQVFzRkFEQWEKTVJnd0ZnWURWUVFERXc5b1lYSmliM0l0ZEc5clpXNHRZMkV3SGhjTk1qVXdOVEkyTURneU1ESXlXaGNOTWpZdwpOVEkyTURneU1ESXlXakFhTVJnd0ZnWURWUVFERXc5b1lYSmliM0l0ZEc5clpXNHRZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURCOVZRLzVqei93ZkdBT2MxS05yV0dqNlBBZHFocjNFZDAKSTFNWU04VVFVWXY1YUhEVE02MDNCc3VzSmQ5NWtQZHQzN1liMGx1TG1PQjd5R1VaMFJsMnhsNHV6cUZvaUs3bQpNcC8rL1NIY2h5aGxib1p5RXdPOXVwNlhZNkhRNmpwZDFLK2dNNTB1Y296azVjMFBsMVZTelF5TE9rcFVzVHdkClRJY0pkZ0ZGaUhmc2RURllJMDZiSDJMK0xRc25tUTVRdDhZYVROQ0ZXWCtHNGxuekVHNEtsWFk2NFlBWFNPVW8KdEY2RXpnQ1pWQUt5Ykp4bEtLSVg3SWI3VkdIZHg4Wmx4b0xsc29RWTRKMG5rM0MzdG1RUGQ1Y29SakFGWnR4ZApTaUUvc0d4eXlRbGVSa2wvNXZCR01lV0NiQnByTVJCY0ZNQ2JidnZNWlFnVDJMWFlNQlZ4QWdNQkFBR2pZVEJmCk1BNEdBMVVkRHdFQi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXcKRHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVOVFSam11aUZCUHlVUVJ5OUhVVXlZMm9ESk4wdwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjA4SlVPNTIxN3dGTCtiZzRKTS91Y1pidWxSc2REUnlodHRPMXlrCmtYbGp0UWJsQ3RsTEViVmdWaElYRy9uR3VKcWduR2h0OEhSSFU3NlVuY1BrcDdIMFdwYmFxOGg2bnBzL01URFMKalhDdmZycStCZmhUZS8zNytxaXBqL2dpYnNEb0g5dlZCeTk1aHREZy9NZ1ZsdThmb1ZBd09GOHNNUGtFbXp6ago3N2F4S2ZPa1lKak80RU9kNGV1bUFnNmpLbDJiREtxNXhldGQ4YlY2RXZRbGQvVHFIRWpNVFhodEptSWprTzZQCnJaeTBRZkFtT0F0b3BXdjIzM291ZmNkWnM3ZVJJNjF3UjkzWWlYNzJUaHh4YWdPL3piYnRpKzBLUUF3WmJDbk8KQkdpb3ZjVkcyN21qQi9uVmZJNE9EUUZxei9KL212OEE4UEJHZ3Zrc3puSDZxT1U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  HARBOR_ADMIN_PASSWORD: "Q2hhbmdlVGhpc1Bhc3N3b3Jk"
  POSTGRESQL_PASSWORD: "Y2hhbmdlaXQ="
  REGISTRY_CREDENTIAL_PASSWORD: "aGFyYm9yX3JlZ2lzdHJ5X3Bhc3N3b3Jk"
  CSRF_KEY: "MmRkRUJpYndDbVU1WGFjM2dKTXg4NTlocnVNUjJpTXE="
---
# Source: harbor/templates/database/database-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-database"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  POSTGRES_PASSWORD: "Y2hhbmdlaXQ="
---
# Source: harbor/templates/ingress/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-ingress"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lSQVBuUUxOWDdmRmNjVnVFM0FtUDVTRlF3RFFZSktvWklodmNOQVFFTEJRQXcKRkRFU01CQUdBMVVFQXhNSmFHRnlZbTl5TFdOaE1CNFhEVEkxTURVeU5qQTRNakF5TWxvWERUSTJNRFV5TmpBNApNakF5TWxvd0lURWZNQjBHQTFVRUF4TVdhR0Z5WW05eUxuUnliMk5vWVd4aGEybHpMbTVsZERDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU0wRm1HUEp5aGRROUc1S2MyaXovRHp2Y21MZkJ6YmUKWEl5Wk1HZE4rbmVwanFlWER0OVh6QUp6bUw2UWFxdUpiNlhFZ3AzVnFIUTdQeUFUdk0raWUzTnYyZWIyVUc3UgpQcDJkSmsrZnZWTjV1VFFuTU5ydFVmOXdWLzAwcHlHWnB5ZzF4TVlhSVZiMHA2REkxeVdhK1dMMHlEUlRLdTY1CnBGN3ZTMW5WTGY5UGpqSmRxby92MDQwc0RKSmVDeUhVRSt6dzZQNjk0OFFQTzAxbVhodDRxQUt0eVU1eGRqSU0KT3ZEanR5TWFJNmFVSzR1elVFT1EyaGtiSC8vazNnMHc0RnFzMUdtV3UrMDhWL1VMM1cwNmlIZ2ZRVUtOR3FiNApkVjdiMnlzbXVab2lnUHZxcm1hdWJTQjJNZUVqT21lWVMyOWxMQThpQ3RJc3NSRG40dFo0eGs4Q0F3RUFBYU9CCmhEQ0JnVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVXRhcGc4RlE5cHBqUmZoOUhiOCtuY2tnUgo4UzR3SVFZRFZSMFJCQm93R0lJV2FHRnlZbTl5TG5SeWIyTm9ZV3hoYTJsekxtNWxkREFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQWhJRms5WEVqTENERTdQK3NlUXFVYWFkZGM3YnI3STJoUVNicU50eEliNTMwRzFRRXV3RFoKeEY2dkRPV2NTbmlQL1pWVk4vZWhqV1VXUnJOajlxcFhwSHk0TlVGb0hUVFRZdy9JZ3dyWWUra2l3YXFSQnFVNQo0L0JZcWFmMEJDN3ZQV3ZWNHQyS2RLZkgySmQ4enloNUZ4Z1ErT3VjdWUrRjFXdFRsd2FSdnlXRDVkYkw1QndaCk9oWjEyM09iTWVrK3ZtcCtMMlRtL3Z0dkdhMlpnNHRzbnJ4ZkhoRmZ4aGNkNENCUjd3TGdWZkFteTFkL1Bab0MKTU9LT084bUdGYmx3R2VxU2k2dkRNNmdYcVdnWUkrUXQzTkdIQjlGdy9iR0JRcTBBWDV6N3MwaE04UVEyZFdpbgpHcm16blNzbUkvQ01DZCtKVmRiMVRSTnJlYkplT0tmeVh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  tls.key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBelFXWVk4bktGMUQwYmtwemFMUDhQTzl5WXQ4SE50NWNqSmt3WjAzNmQ2bU9wNWNPCjMxZk1Bbk9ZdnBCcXE0bHZwY1NDbmRXb2REcy9JQk84ejZKN2MyL1o1dlpRYnRFK25aMG1UNSs5VTNtNU5DY3cKMnUxUi8zQlgvVFNuSVptbktEWEV4aG9oVnZTbm9NalhKWnI1WXZUSU5GTXE3cm1rWHU5TFdkVXQvMCtPTWwycQpqKy9UalN3TWtsNExJZFFUN1BEby9yM2p4QTg3VFdaZUczaW9BcTNKVG5GMk1ndzY4T08zSXhvanBwUXJpN05RClE1RGFHUnNmLytUZURURGdXcXpVYVphNzdUeFg5UXZkYlRxSWVCOUJRbzBhcHZoMVh0dmJLeWE1bWlLQSsrcXUKWnE1dElIWXg0U002WjVoTGIyVXNEeUlLMGl5eEVPZmkxbmpHVHdJREFRQUJBb0lCQUFvOHk4bTcwMGdMeGxEVgpqZUsrRGd2YTV3clIyVEhmczU1ZnJkK1NzTDJWN1dZbjhGbXRzQ1cxTVB6ZkNEeU5qZElvdUY3NlFzR2ZEYjFqCnp1dE5VVDNINllrVFpwdkovZ2J2eUhCMGFRZElqanR3ODRzVEM2T21ML2FZVVBvb0NvVkMvaExvVGg3aDg1YmYKUUlNRHRJMUE3TmhVQ05KSDJkSFZ3Qno1dktUQmRNY05EcnRYOXZFYXZ5MWdZVFNUWmZ3WWliU2V2aEZwZjJ6SAo5Ykt2S2JrWTdyeFJlYXVmdVFnTDdpYXBIWlpPZXpqTW5mVTJZNnk5OXJvbXQ2L2hLd3VBaTBEOTVQR3lEUG9DCmxrRk0vbzZtTG94aGc5YjVxZG1zNUpTOHRCVnhIZkRRUkFsTFpqbDhzNCtvZEhWUWU0UndyUkkyY0JxKzdjMVkKSmorL0I5RUNnWUVBMVFNa2M4MGU0YVZTaDRyZjJMZHU4RGdRQkZiTzdwaGZUYkFUL2J5dlJyL2tRbm1ON2QyMQpZWXhuTDVGUXo1bnA5WjFXeVZMcWFtM2RCR0IwQ09YdlhCMXVudG9DN1JUMXZCamFNVGNLZEVKSTdHNXpsVUJLCkYvdnZrQ016L01BRklnUzIrdDZjU3RZRkorSjUwYm9aSFVBR0Z5RmRBbWh0QWRPWWJrdG9FVEVDZ1lFQTltV2sKeXo2c24vN3pnaUFOVHRyVzFyRWZMWTFEQ2FkNk10TCt0cTduRXhkUnovUnY2YmNTSnpVOWJHclk2bFMxQ3dCVAp5TncwbjdDL0w1bmFEN3ordDA3K1pRRE00VXl0MFJiY0hDb0xBcGtNNFRRQWVKS1JDd1o2WDZKRTVBaGU1Vk82CnA5N3ltMUZlMk9yOGVrSUVRa0dwVzZmQlZOTytuK3l6V0R1a2IzOENnWUJBclVxVktyUDB1WmpjZE90UXh5bVYKSU1Da1FLTm1TTGV2UkFaZDVidW1sTDgrKzk5L1dQRW81Rk8wV3NBWnVOY1Q3NmtaU2ViSldBQml3dEtZblJCWApmTXhJeVZOWUh5UVo3OFhZYWFqdjhleG9kWVQ4elY5eDl0b2Zmc0RiUG9hUWRMUUdhaTgwZmRWazdkd2xOUWRKCkhWWjhFWEpITitQWlNTRWdaQjcrRVFLQmdRQ2krRm5HUUg4SEdDZFJzd2Q2VjQ1djFCa3VGTmY1UTdlMGRCQWIKSHBZaDczT2lXeWZHYXRycjZlL2xqTXBLTzVxL1d3a1B1bTVvRFF4M1hJaDVqbVRmTTdWWmN1MFFPNXBmeUlIdgpjdk56VlczS2FvM0JNaGdUTmNhdENIUU9hMmJ3d2ErY3B2N0tNa2pNcXFneDZRWk9HSVgrNUhjZ055bEhOOVRyCmtBOVQyd0tCZ0JYbE5xcGVPM0JGL2psUXE0cENrU0NuZi9aQzJNSmI1b21ESFl2R2ZxRDlwWjA3eWY0REszWGgKRzNac3V0NXUwdGhFWXJadE52a2RObTRoUThiY1pEUmcvU21sK1plb3prRFFvYzh1cXdWU25PbUtndUprQTJUTAorTGkzNU1HeCtMSHJFQnNPVTNMbjhtY1FBbk9XV3JNSldoaFhpVkZSb1ZISE1Od21nOUpMCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
  ca.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lRVGJWcmJ1M1hJZ0wrTVUxcHNvYlA3REFOQmdrcWhraUc5dzBCQVFzRkFEQVUKTVJJd0VBWURWUVFERXdsb1lYSmliM0l0WTJFd0hoY05NalV3TlRJMk1EZ3lNREl5V2hjTk1qWXdOVEkyTURneQpNREl5V2pBVU1SSXdFQVlEVlFRREV3bG9ZWEppYjNJdFkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRQ3VNWGhzSStBS01TNUV0dXFhVUs4dExyV2kvWG1keTg4bXdPdlpvSkRFTmxwNDVCWHMKb1NYMHJyTkJRT1J0dEt4KzBHVlgzUSs1enZZZFhwelhYUzFOZUw2QnZYQ0I2ekdyU1BBSGc5MEgxcHptdXVWZQpZNmVOMFBKVk9DeEoxSGZnaUJPVGJDRE01ZHNEUis0TDJsZlFJSUVIazNidDdUaGlIY1hqWUpkRjltRTlaNnR4CllKdXpqOXBXcnBJQ1ZkTS9RaFkyUHVoczdEVEtKR1VSMlZwc3E4Q3hEdndMVXptVEQrWnFlUmd5NFJpQThQYnQKRWxQN0VhTEM5RnFLMmR2VkE4WWd6bWFOS1F0QTFwTEFYb0FhUXJ5ZTBwdWNmbjR1NmRYd3lveGJxd01MaklSZQpLRysxWHBwek4xbklVTlFvMDlHUXgyVFR4M3pubkY2RFVpT2RBZ01CQUFHallUQmZNQTRHQTFVZER3RUIvd1FFCkF3SUNwREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXcKQXdFQi96QWRCZ05WSFE0RUZnUVV0YXBnOEZROXBwalJmaDlIYjgrbmNrZ1I4UzR3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFGdXRUSUo1K3lhdmxTMUhjVVZPa21oTm5HVHFWZ0ZNd3hWamtnMVFMbERNcU4zZnM0L09CbzB0CkpuUTcwNmdpZFdRa25NY25qRHBaajlBUjFGckVCMVJscU10NHJPSFBwRlpVek4zanVMQjc4Z1ZRaW9sc3dqclEKaFBVZGQ5aVRyREpRcE1mYmU1UG9SWU1jU210U1lJNjk1ck9PRjU4MHZSQ25PWWxJaWNIMzZFN2g0ZXpNSUE0Swp2MlZBc3NQWC8rbzZGL1FyM1p5ZEpNRU1oeEwzTjVXdkdzeFlhY1V3UFp1R2gxS1JKc2FZSnlwTmY3VDlQNUE2CjdCTnVlZ0tuTjRWZjJwNGtPRk1MYlNTclJHbXlaYkpvYld5L3hTL2FBNzJ4emRjOVZNNVlNa2xhVjlRdXdPLzIKZ09VeDhDczBMd2hpUGxMelZCMi9XekZVMFRqY2Jvcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
# Source: harbor/templates/jobservice/jobservice-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-jobservice"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  JOBSERVICE_SECRET: "S0RLb3NIVGd3WUxZNEhvRA=="
  REGISTRY_CREDENTIAL_PASSWORD: "aGFyYm9yX3JlZ2lzdHJ5X3Bhc3N3b3Jk"
---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-registry"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "b0dhZ2ViYU4wUG5EdGhJMw=="
  REGISTRY_REDIS_PASSWORD: ""
---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-registry-htpasswd"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTPASSWD: "aGFyYm9yX3JlZ2lzdHJ5X3VzZXI6JDJhJDEwJFhGaHZqVzdqeUFCbXFpaVdQRzJBSmUyaUNYbWxiQWtwendoSFhDNFdBNlNhdjBrVVlvYWtX"
---
# Source: harbor/templates/registry/registryctl-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-registryctl"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
---
# Source: harbor/templates/trivy/trivy-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-trivy
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  redisURL: cmVkaXM6Ly9oYXJib3ItcmVkaXM6NjM3OS81P2lkbGVfdGltZW91dF9zZWNvbmRzPTMw
  gitHubToken: ""