apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: trochalakisnet-issuer
spec:
  acme:
    email: admin@trochalakis.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: admin@trochalakis.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
